import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpRight, Check, ChevronDown, CircleHelp, Copy, Database, FileSearch, Gauge, HardDrive, KeyRound, Layers3, LockKeyhole, MoreHorizontal, Network, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, X } from 'lucide-react';

type NodeInfo={id:string;domain:string;state:string;usedBytes:number;objects:number};
type Overview={cluster:{state:string;nodesHealthy:number;nodesTotal:number;objects:number;usedBytes:number;uptimeSeconds:number};nodes:NodeInfo[];policy:{replicas:number;writeAcks:number};repairBacklog:number;repairCompleted:number;repairError:string;requests:number};
const fallback:Overview={cluster:{state:'HEALTHY',nodesHealthy:3,nodesTotal:3,objects:0,usedBytes:0,uptimeSeconds:0},nodes:[],policy:{replicas:3,writeAcks:2},repairBacklog:0,repairCompleted:0,repairError:'',requests:0};
const tokenKey='vault-admin-token';
function fmtBytes(v:number){if(!v)return '0 B';const u=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(v)/Math.log(1024)),4);return `${(v/1024**i).toFixed(i?1:0)} ${u[i]}`}
function fmtDuration(s:number){const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?`${d}d ${h}h`:`${h}h ${m}m`}
function App(){
 const [token,setToken]=useState(localStorage.getItem(tokenKey)||'dev-vault-token');const [data,setData]=useState<Overview>(fallback);const [err,setErr]=useState('');const [key,setKey]=useState('');const [object,setObject]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [authOpen,setAuthOpen]=useState(false);const [nav,setNav]=useState('Overview');
 const headers=useMemo(()=>({'Authorization':`Bearer ${token}`}),[token]);
 function navigate(label:string){setNav(label);const target:Record<string,string>={Objects:'#objects', 'Storage nodes':'#nodes', 'Repair & rebalance':'#repair', Settings:'#policy', Overview:'#top'};document.querySelector(target[label]||'#top')?.scrollIntoView({behavior:'smooth',block:'start'})}
 async function refresh(){try{const r=await fetch('/api/ops/overview',{headers});if(r.status===401){setErr('Authentication failed. Check the operator token.');return}if(!r.ok)throw new Error('Could not reach the Vault control plane');const d=await r.json();setData(d);setErr('')}catch{setErr('API unavailable · showing last known state')}}
 useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),5000);return()=>clearInterval(t)},[token]);
 async function nodeAction(id:string,action:'drain'|'restore'){setBusy(true);try{const r=await fetch(`/api/nodes/${id}/${action}`,{method:'POST',headers});if(!r.ok)throw new Error(await r.text());setNotice(`${id} ${action==='drain'?'drain started':'restored'}`);await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Action failed')}finally{setBusy(false);setTimeout(()=>setNotice(''),3800)}}
 async function lookup(e:React.FormEvent){e.preventDefault();if(!key.trim())return;setBusy(true);try{const r=await fetch(`/api/objects/${encodeURIComponent(key)}`,{method:'HEAD',headers});if(r.ok)setObject(`${key} · generation ${r.headers.get('ETag')?.replaceAll('"','')} · ${r.headers.get('X-Content-SHA256')?.slice(0,16)}…`);else setObject(r.status===404?'Object not found':`Lookup failed (${r.status})`)}catch{setObject('API unavailable')}finally{setBusy(false)}}
 async function saveToken(e:React.FormEvent){e.preventDefault();localStorage.setItem(tokenKey,token);setAuthOpen(false);await refresh()}
 const healthy=data.cluster.nodesHealthy;const state=data.cluster.state?.toLowerCase()||'healthy';const percent=Math.min(100,Math.round(healthy/Math.max(data.cluster.nodesTotal,1)*100));
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><Layers3 size={19}/></div><span>vault<span className="brand-dot">.</span></span><button className="icon-btn sidebar-collapse" aria-label="Collapse sidebar"><ChevronDown size={16}/></button></div>
   <div className="workspace"><div className="workspace-icon">P</div><div><b>Production</b><small>us-east · cluster-01</small></div><ChevronDown size={15}/></div>
   <div className="nav-caption">WORKSPACE</div><nav>{[[Gauge,'Overview'],[Database,'Objects'],[HardDrive,'Storage nodes'],[Activity,'Repair & rebalance']].map(([Icon,label])=><button key={label as string} onClick={()=>navigate(label as string)} className={`nav-item ${nav===label?'active':''}`}><Icon size={17}/><span>{label as string}</span>{label==='Repair & rebalance'&&data.repairBacklog>0?<em>{data.repairBacklog}</em>:null}</button>)}</nav>
   <div className="sidebar-bottom"><div className="nav-caption">SYSTEM</div><button className="nav-item" onClick={()=>navigate('Settings')}><Settings2 size={17}/>Settings</button><button className="nav-item" onClick={()=>setAuthOpen(true)}><KeyRound size={17}/>Operator access</button><div className="sidebar-help"><div className="help-icon"><CircleHelp size={17}/></div><div><b>Need a hand?</b><small>Explore the quick guide</small></div><ArrowUpRight size={15}/></div><div className="user-card"><div className="avatar">OP</div><div className="user-meta"><b>Vault operator</b><small>Administrator</small></div><MoreHorizontal size={17}/></div></div>
  </aside>
  <main className="main"><header className="topbar" id="top"><div className="breadcrumbs"><span>Vault</span><span className="slash">/</span><b>{nav}</b></div><div className="top-actions"><div className="live-pill"><span className="pulse-dot"/>Live updates</div><button className="icon-btn" title="Refresh" onClick={()=>void refresh()}><RefreshCw size={16}/></button><button className="icon-btn help-top" title="Help"><CircleHelp size={17}/></button><div className="top-avatar">OP</div></div></header>
   <div className="content"><div className="page-intro"><div><div className="eyebrow"><span className="sparkle"><Sparkles size={13}/></span>YOUR STORAGE, IN SYNC</div><h1>{nav==='Overview'?'Good morning, operator':nav}<span className="heading-period">.</span></h1><p className="subtitle">{state==='healthy'?'A clear view of your cluster. Everything is where it should be.':'Cluster health needs attention. Review the signals below.'}</p></div><div className="intro-right"><span className="updated"><span className="tiny-pulse"/>Updated just now</span><button className="refresh-btn" onClick={()=>void refresh()}><RefreshCw size={15}/> Refresh</button></div></div>
   {err&&<div className="alert"><span className="alert-dot"/>{err}<button onClick={()=>void refresh()}>Retry</button></div>}{notice&&<div className="toast"><Check size={16}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={15}/></button></div>}
   <section className={`hero-card hero-${state}`}><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="hero-grid"/><div className="hero-left"><div className="hero-label"><span className="hero-status-dot"/>CLUSTER STATUS <span className="hero-sep">/</span> {data.cluster.nodesTotal} NODES</div><div className="hero-title">Everything is <span>{state==='healthy'?'healthy':state==='degraded'?'recovering':'offline'}.</span></div><p>Your data is replicated, verified, and ready when you are.</p><div className="hero-facts"><span><ShieldCheck size={15}/>Strong consistency</span><span><Network size={15}/>{data.policy.replicas}× replication</span><span><LockKeyhole size={14}/>Atomic metadata writes</span></div></div><div className="health-visual"><div className="health-ring"><svg viewBox="0 0 120 120"><circle className="ring-track" cx="60" cy="60" r="51"/><circle className="ring-value" cx="60" cy="60" r="51" style={{strokeDasharray:`${percent*3.2} 320`}}/></svg><div className="ring-center"><b>{healthy}<span>/{data.cluster.nodesTotal}</span></b><small>NODES UP</small></div></div><div className="health-caption"><span className="pulse-dot"/>{state==='healthy'?'All systems operational':state==='degraded'?'Some nodes need attention':'Cluster unavailable'}</div></div></section>
   <div className="section-head"><div><h2>At a glance</h2><p>The numbers that matter, without the noise.</p></div><button className="text-link" onClick={()=>navigate('Storage nodes')}>View cluster <ArrowUpRight size={15}/></button></div>
   <section className="metrics-grid"><Metric icon={<Database size={17}/>} label="Stored objects" value={data.cluster.objects.toLocaleString()} foot="Across your cluster" tone="purple" delay="1"/><Metric icon={<HardDrive size={17}/>} label="Storage used" value={fmtBytes(data.cluster.usedBytes)} foot="Verified across replicas" tone="blue" delay="2"/><Metric icon={<RefreshCw size={17}/>} label="Repair queue" value={String(data.repairBacklog)} foot={data.repairBacklog?'Attention needed':'All replicas in sync'} tone="green" delay="3"/><Metric icon={<Activity size={17}/>} label="Cluster uptime" value={fmtDuration(data.cluster.uptimeSeconds)} foot={`${data.requests.toLocaleString()} requests served`} tone="amber" delay="4"/></section>
   <section className="lower-grid"><div className="panel nodes-panel" id="nodes"><div className="panel-head"><div><h2>Storage nodes</h2><p>Spread across independent failure domains</p></div><button className="panel-link" onClick={()=>navigate('Storage nodes')}>See all <ArrowUpRight size={14}/></button></div><div className="node-list">{(data.nodes.length?data.nodes:[]).map((n,i)=><div className="node-row" key={n.id} style={{animationDelay:`${i*75}ms`}}><div className={`node-icon ${n.state==='healthy'?'node-ok':'node-warn'}`}><HardDrive size={17}/></div><div className="node-name"><b>{n.id}</b><small>{n.domain} · {fmtBytes(n.usedBytes)}</small></div><div className={`status-chip ${n.state==='healthy'?'':'status-warn'}`}><span/>{n.state}</div><button className="node-action" onClick={()=>void nodeAction(n.id,n.state==='healthy'?'drain':'restore')} disabled={busy}>{n.state==='healthy'?'Drain':'Restore'}</button></div>)}{!data.nodes.length&&<div className="empty-nodes"><div className="mini-skeleton"/><span>Connecting to storage nodes…</span></div>}</div><div className="panel-foot"><div className="failure-domains"><span className="domain-dot"/><span className="domain-dot"/><span className="domain-dot"/><span>3 independent failure domains</span></div><span className="foot-link">Auto-healing <span className="on-label">ON</span></span></div></div>
   <div className="panel integrity-panel" id="repair"><div className="panel-head"><div><h2>Data integrity</h2><p>Continuous verification, quietly working</p></div><div className="shield-badge"><ShieldCheck size={17}/></div></div><div className="integrity-art"><div className="integrity-ring ring-one"/><div className="integrity-ring ring-two"/><div className="integrity-core"><Check size={23}/></div><div className="float-chip chip-a"><span className="chip-dot"/>SHA-256 verified</div><div className="float-chip chip-b"><Check size={12}/>Replica healthy</div></div><div className="integrity-bottom"><div><b>{data.repairBacklog?'Repair in progress':'All clear'}</b><small>{data.repairCompleted} repairs completed</small></div><div className="integrity-score">{data.repairBacklog?'…':'100'}<span>{data.repairBacklog?'':'%'}</span></div></div><div className="integrity-bar"><span/></div></div></section>
   <section className="bottom-grid"><div className="panel object-panel" id="objects"><div className="panel-head"><div><h2>Find an object</h2><p>Look up an object's current generation</p></div><div className="search-mark"><FileSearch size={18}/></div></div><form className="lookup-form" onSubmit={lookup}><Search size={16}/><input aria-label="Object key" placeholder="Enter an object key…" value={key} onChange={e=>setKey(e.target.value)}/><button disabled={busy||!key.trim()}>Look up <ArrowUpRight size={14}/></button></form>{object&&<div className="lookup-result"><Check size={14}/><span>{object}</span><button onClick={()=>void navigator.clipboard?.writeText(object)} title="Copy"><Copy size={13}/></button></div>}</div><div className="panel policy-panel" id="policy"><div className="panel-head"><div><h2>Durability policy</h2><p>Your default protection settings</p></div><div className="policy-badge"><LockKeyhole size={16}/></div></div><div className="policy-row"><div className="policy-symbol">{data.policy.replicas}<span>×</span></div><div><b>Replica copies</b><small>Across separate failure domains</small></div><div className="policy-divider"/><div className="policy-symbol">{data.policy.writeAcks}<span>/{data.policy.replicas}</span></div><div><b>Write acknowledgements</b><small>Durable copies before success</small></div></div><div className="policy-foot"><span><span className="policy-live"/>Policy active</span><span>Updated automatically</span></div></div></section>
   <footer><div className="footer-brand"><span className="footer-mark"><Layers3 size={12}/></span>Vault <span className="footer-version">CONTROL PLANE · V0.1</span></div><div className="footer-right"><span><span className="footer-live"/>Coordinator online</span><span className="footer-sep">·</span><span>Uptime {fmtDuration(data.cluster.uptimeSeconds)}</span></div></footer>
   </div>
  </main>
  {authOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAuthOpen(false)}}><form className="auth-modal" onSubmit={saveToken}><button type="button" className="modal-close" onClick={()=>setAuthOpen(false)}><X size={17}/></button><div className="auth-icon"><KeyRound size={20}/></div><h2>Operator access</h2><p>Enter the bearer token configured for this Vault control plane.</p><label>ADMIN TOKEN<input autoFocus type="password" value={token} onChange={e=>setToken(e.target.value)}/></label><button className="save-token">Save access token <ArrowUpRight size={15}/></button></form></div>}
 </div>
}
function Metric({icon,label,value,foot,tone,delay}:{icon:React.ReactNode;label:string;value:string;foot:string;tone:string;delay:string}){return <div className={`metric-card metric-${tone}`} style={{animationDelay:`${Number(delay)*90}ms`}}><div className="metric-top"><div className="metric-icon">{icon}</div><span className="metric-kicker">LIVE</span></div><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-foot"><span className="metric-footdot"/>{foot}</div></div>}
export default App;
